services:
  haskell:
    image: rust
    container_name: paiza.haskell
    network_mode: bridge
    stdin_open: true
    working_dir: /root/app
    volumes:
      - .:/root/app
      - haskell.vscode-server:/root/.vscode-server
      - haskell.ghcup:/root/.ghcup
    environment:
      PATH: "/root/.ghcup/bin:$PATH"
      http_proxy: http://192.168.31.2:10801
      https_proxy: http://192.168.31.2:10801
    command: ghci
  lean:
    image: rust
    container_name: paiza.lean
    network_mode: bridge
    stdin_open: true
    working_dir: /root/app
    volumes:
      - .:/root/app
      - lean.vscode-server:/root/.vscode-server
      - lean.elan:/root/.elan
    environment:
      PATH: "/root/.elan/bin:$PATH"
      http_proxy: http://192.168.31.2:10801
      https_proxy: http://192.168.31.2:10801
  scala:
    image: sbtscala/scala-sbt:eclipse-temurin-23.0.1_11_1.10.7_2.12.20
    command: ["scala"]
    container_name: paiza.scala
    stdin_open: true
    working_dir: /root/app
    network_mode: bridge
    volumes:
      - .:/root/app
      - scala.vscode-server:/root/.vscode-server

volumes:
  haskell.vscode-server:
  haskell.ghcup:
    external: true
  lean.vscode-server:
  lean.elan:
    external: true
  scala.vscode-server:
